#端口，项目上下文根
server:
  port: 8087
  servlet:
    context-path: /middleware
    
#配置mybatis
mybatis:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
   #配置实体类的别名
  type-aliases-package: pojo
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true


    

#配置mysql连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  
  ## Redis 配置
  redis:
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码
    password:


  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

